version: '3'

services:
  biblio_app:
    container_name: biblio
    restart: always
    build: ./flask_app
    links:
      - dbmysql
    ports:
      - "5000:5000"
    depends_on:
      - dbmysql
      - redis
    networks:
      - biblio_net

  nginx:
    image: nginx:latest
    container_name: nginx_biblio
    restart: always
    working_dir: "/var/www"
    volumes:
      - "./:/var/www"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8000:80"
    depends_on:
      - biblio_app
    command: [nginx-debug, '-g', 'daemon off;']
    networks:
      - biblio_net

  dbmysql:
    image: mysql:5.7
    container_name: mysql_biblio
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: bibliodb
      MYSQL_ROOT_PASSWORD: motpass
      MYSQL_USER: pross
      MYSQL_PASSWORD: motpass
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d/:rw
      - mysql-data:/var/lib/mysql
    networks:
      - biblio_net

  redis:
    image: redis:latest
    container_name: redis_biblio
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - biblio_net

volumes:
  mysql-data:
  redis-data:

networks:
  biblio_net:
    driver : bridge